server:
  port: 3000

eureka:
  server:
#    enable-self-preservation: false #关闭自我保护机制
#    eviction-interval-timer-in-ms: 4000 #设置清理间隔(单位:毫秒 默认是60*1000)

  #在/etc/hosts中添加
  #127.0.0.1 eureka1
  #127.0.0.1 eureka2
  instance:
    hostname: eureka1

  client:
#    registerWithEureka: false #不把自己作为一个客户端注册到自己身上
#    fetchRegistry: false #不需要从服务端获取注册信息(因为在这里自己就是服务端,而且已经禁用自己注册了)
    serviceUrl:
      defaultZone: http://eureka2:3001/eureka #要配集群，不需要注册自己，注册其他就行，还有其他，逗号分割

spring:
  application:
    name: eureka
